# Generated by Django 5.1.2 on 2025-04-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(blank=True, choices=[('fixed', 'Fixed Price'), ('range', 'Price Range'), ('custom', 'Custom Quote')], default='fixed', max_length=20, verbose_name='Price Type')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for the service', max_digits=10, verbose_name='Base Price')),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for price range type', max_digits=10, null=True, verbose_name='Minimum Price')),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price for price range type', max_digits=10, null=True, verbose_name='Maximum Price')),
                ('title', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=200, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, upload_to='images/service_categories', verbose_name='Category Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('min_guests', models.PositiveIntegerField(blank=True, default=1, help_text='Minimum number of guests required', null=True, verbose_name='Minimum Guests')),
                ('max_guests', models.PositiveIntegerField(blank=True, help_text='Maximum number of guests allowed', null=True, verbose_name='Maximum Guests')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/services/gallery', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Image Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='services_module.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
            },
        ),
    ]
