# Generated by Django 5.1.2 on 2025-04-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0002_menu_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('main', 'Main Gallery'), ('slider', 'Slider Images'), ('background', 'Background Images'), ('featured', 'Featured Images'), ('other', 'Other Images')], default='main', help_text='Category to filter images in different templates', max_length=20, verbose_name='Image Category'),
        ),
    ]
