# Generated by Django 5.1.2 on 2025-04-20 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_module', '0003_gallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='services_module.service', verbose_name='Service'),
        ),
    ]
