# Generated by Django 5.1.2 on 2025-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('site_url', models.CharField(max_length=200, verbose_name='Site URL')),
                ('site_logo', models.ImageField(blank=True, upload_to='images/site_module', verbose_name='Site Logo')),
                ('site_phone', models.CharField(blank=True, max_length=50, verbose_name='Site Phone')),
                ('site_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('site_address', models.TextField(blank=True, verbose_name='Site Address')),
                ('site_copyright', models.TextField(blank=True, verbose_name='Site Copyright')),
                ('is_main_setting', models.BooleanField(default=True, verbose_name='Main Setting')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
