# Generated by Django 5.1.2 on 2025-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='site_favicon',
            field=models.ImageField(blank=True, upload_to='images/site_module', verbose_name='Site Favicon'),
        ),
    ]
